title: Francesco Petriglia
logo: https://github.com/FraPet/portfolio-new/assets/38542557/070f91d0-631c-407a-b1a4-5bbc192f8e34
description: "I'm a data scientist with expertise in computational linguistics, natural language processing (NLP), machine learning (ML), healthcare, and language disorders. I combine my background in psychological sciences and speech therapy with data science to create impactful solutions."
theme: jekyll-theme-minimal
