title: Francesco Petriglia
logo: https://github.com/FraPet/portfolio-new/blob/main/assets/profilo_tonda.jpg?raw=true
description: I'm a data scientist with expertise in computational linguistics, natural language processing (NLP), machine learning (ML), healthcare, and language disorders. I combine my background in psychological sciences and speech therapy with data science to create impactful solutions.
theme: jekyll-theme-minimal
